AllCops:
  TargetRubyVersion: 3.0
  Include:
    - 'lib/**/*'
    - 'spec/**/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/Documentation:
  Exclude:
    - '**/*'

Metrics/MethodLength:
  Max: 30